apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingenieria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingenieria
  template:
    metadata:
      labels:
        app: ingenieria
    spec:
      containers:
      - name: ingenieria
        image: gcr.io/[YOUR_PROJECT_ID]/ingenieria:v1
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"