apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer1
  labels:
    app: consumer1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer1
  template:
    metadata:
      labels:
        app: consumer1
    spec:
      containers:
      - name: consumer1
        image: gcr.io/[YOUR_PROJECT_ID]/consumer1:v1
        env:
        - name: KAFKA_BROKER
          value: "kafka-service:9092"  # Dirección de Kafka en Kubernetes
        - name: REDIS_ADDR
          value: "redis-service:6379"  # Dirección de Redis en Kubernetes
