apiVersion: apps/v1
kind: Deployment
metadata:
  name: natacion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: natacion
  template:
    metadata:
      labels:
        app: natacion
    spec:
      containers:
      - name: natacion
        image: gcr.io/[YOUR_PROJECT_ID]/natacion:v1
        ports:
        - containerPort: 8082
        env:
        - name: KAFKA_BROKER
          value: "kafka-service:9092"  # Dirección de Kafka en Kubernetes
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: natacion-service
spec:
  selector:
    app: natacion
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  type: ClusterIP
