apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: olympiadas-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - path: /submitAgronomia
        pathType: Prefix
        backend:
          service:
            name: agronomia-service
            port:
              number: 8080
      - path: /submitIngenieria
        pathType: Prefix
        backend:
          service:
            name: ingenieria-service
            port:
              number: 8081
