version: '3'
services:  
  logs:    
    build:
      context: ./
      dockerfile: Dockerfile.AdminLogs
    ports:      
      - "8000:8000"    
    volumes:        
      - ./app/logs.json:/app/logs.json      
      - ./app/level_distribution.png:/app/level_distribution.png      
      - ./app/logs_per_hour.png:/app/logs_per_hour.png